title: Covid Heroes
url: "https://covid-heroes.com"
baseurl: ""
timezone: America/Los_Angeles

permalink: pretty

collections:
  heroes: 
    sort_by: last_name
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "heroes"
    values:
      layout: "hero"

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sass:
    style: compressed
    sass_dir: _sass

# Exclude from processing
exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - vendor
  - webpack.config.js
  - README.md
  - LICENSE.md
  - CONTRIBUTE.md