title: Covid Heroes
baseurl: ""
url: ""
timezone: America/Los_Angeles

permalink: pretty

collections:
  heroes: 
    sort_by: death_date DESC
    output: true
    permalink: :name

sass:
    style: compressed
    sass_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "heroes"
    values:
      layout: "hero"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  
exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - vendor
  - webpack.config.js
  - README.md
  - LICENSE.md
