title: Covid Heroes
url: "https://covid-heroes.com"
baseurl: ""
timezone: America/Los_Angeles

permalink: pretty

# Build Settings
markdown: kramdown

plugins:
  - jekyll-airtable
  - environment_variables_generator
  
airtable:
  enable_sync: true
  base_uid: 'appgqOzXOkm2bsEE6'
  tables:
    - name: 'Active'
      text_columns:
        - 'first_name'
        - 'last_name'
        - 'slug'
        - 'occupation'
        - 'employer'
        - 'city'
        - 'province'
        - 'country'
        - 'source'
      date_columns:
        - 'birth_date'
        - 'death_date'
      long_text_columns:
        - 'description'
        - 'content'
      attachment_columns:
        - 'portrait'

sass:
    style: compressed
    sass_dir: _sass

collections_dir: heroes
collections:
  heroes: 
    sort_by: last_name
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "Heroes"
    values:
      layout: "hero"

# Exclude from processing
exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - vendor
  - webpack.config.js
  - README.md
  - LICENSE.md
  - CONTRIBUTE.md